### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by capybarin** [ruxxzebre/didactic-spork#1]
Generator throws an error with that JSON:
[
    {
        "eventType": "updatedUser",
        "eventPayload": {
            "changedFields": {
                "unsubscribeReason": {
                    "newValue": "testd",
                    "oldValue": "test"
                },
                "email": {
                    "newValue": "test@maill.org",
                    "oldValue": "test@mail.org"
                },
                "firstName": {
                    "newValue": "rtttt2",
                    "oldValue": "rtttt"
                },
                "lastName": {
                    "newValue": "t2",
                    "oldValue": "t"
                },
                "name": {
                    "newValue": "rt2",
                    "oldValue": "rt"
                },
                "company": {
                    "newValue": "comp1",
                    "oldValue": "comp"
                },
                "website": {
                    "newValue": "exampele.com",
                    "oldValue": "example.com"
                },
                "salutation": {
                    "newValue": "salute",
                    "oldValue": "salut"
                },
                "title": {
                    "newValue": "titlee",
                    "oldValue": "title"
                },
                "leadScore": {
                    "newValue": 5,
                    "oldValue": 4
                },
                "userId": {
                    "newValue": "1234231",
                    "oldValue": "123423"
                },
                "unsubscribed": {
                    "newValue": true,
                    "oldValue": false
                },
                "enchargeAnonymousId": {
                    "newValue": "5",
                    "oldValue": "3"
                },
                "segmentAnonymousId": {
                    "newValue": "5",
                    "oldValue": "3"
                },
                "phone": {
                    "newValue": "1234447852",
                    "oldValue": "123444785"
                },
                "address": {
                    "newValue": "addressd",
                    "oldValue": "address"
                },
                "country": {
                    "newValue": "counrtyd",
                    "oldValue": "counrty"
                },
                "city": {
                    "newValue": "cityd",
                    "oldValue": "city"
                },
                "state": {
                    "newValue": "regiond",
                    "oldValue": "region"
                },
                "postcode": {
                    "newValue": "postcoded",
                    "oldValue": "postcode"
                },
                "groupId": {
                    "newValue": "66663",
                    "oldValue": "6666"
                },
                "referrer": {
                    "newValue": "https://exampl2e.com/",
                    "oldValue": "https://example.com/"
                },
                "firstReferrer": {
                    "newValue": "https://examp2le.com/",
                    "oldValue": "https://example.com/"
                },
                "UTMSource": {
                    "newValue": "https://examp22le.com/",
                    "oldValue": "https://example.com/"
                },
                "UTMMedium": {
                    "newValue": "https://exampl2e.com/",
                    "oldValue": "https://example.com/"
                },
                "UTMTerm": {
                    "newValue": "https://exampl2e.com/",
                    "oldValue": "https://example.com/"
                },
                "UTMContent": {
                    "newValue": "https://example2.com/",
                    "oldValue": "https://example.com/"
                },
                "UTMCampaign": {
                    "newValue": "https://exampl2e.com/",
                    "oldValue": "https://example.com/"
                },
                "firstUTMSource": {
                    "newValue": "https://exampl2e.com/",
                    "oldValue": "https://example.com/"
                },
                "firstUTMMedium": {
                    "newValue": "https://exam2ple.com/",
                    "oldValue": "https://example.com/"
                },
                "firstUTMTerm": {
                    "newValue": "https://exampl2e.com/",
                    "oldValue": "https://example.com/"
                },
                "firstUTMContent": {
                    "newValue": "https://exampl2e.com/",
                    "oldValue": "https://example.com/"
                },
                "firstUTMCampaign": {
                    "newValue": "https://exampl2e.com/",
                    "oldValue": "https://example.com/"
                },
                "ip": {
                    "newValue": "198.168.0.4",
                    "oldValue": "198.168.0.1"
                },
                "platform": {
                    "newValue": "pcd",
                    "oldValue": "pc"
                },
                "browser": {
                    "newValue": "chromed",
                    "oldValue": "chrome"
                },
                "deviceType": {
                    "newValue": "pcd",
                    "oldValue": "pc"
                },
                "device": {
                    "newValue": "pcd",
                    "oldValue": "pc"
                },
                "MRR": {
                    "newValue": 5,
                    "oldValue": 3
                }
            },
            "source": "manual"
        },
        "endUserData": [
            {
                "email": "test@maill.org",
                "firstName": "rtttt2",
                "lastName": "t2",
                "name": "rt2",
                "lastActivity": "2021-02-25T22:00:00.000Z",
                "createdAt": "2021-02-28T10:05:00.000Z",
                "company": "comp1",
                "website": "exampele.com",
                "salutation": "salute",
                "title": "titlee",
                "leadScore": 5,
                "userId": "1234231",
                "updatedAt": "2021-02-04T10:14:44.540Z",
                "unsubscribed": true,
                "id": "958541a8-765f-47f5-b901-0798ca82a7f7",
                "enchargeAnonymousId": "5",
                "segmentAnonymousId": "5",
                "phone": "1234447852",
                "address": "addressd",
                "country": "counrtyd",
                "city": "cityd",
                "state": "regiond",
                "postcode": "postcoded",
                "timezone": "America/New_York",
                "groupId": "66663",
                "referrer": "https://exampl2e.com/",
                "firstReferrer": "https://examp2le.com/",
                "UTMSource": "https://examp22le.com/",
                "UTMMedium": "https://exampl2e.com/",
                "UTMTerm": "https://exampl2e.com/",
                "UTMContent": "https://example2.com/",
                "UTMCampaign": "https://exampl2e.com/",
                "firstUTMSource": "https://exampl2e.com/",
                "firstUTMMedium": "https://exam2ple.com/",
                "firstUTMTerm": "https://exampl2e.com/",
                "firstUTMContent": "https://exampl2e.com/",
                "firstUTMCampaign": "https://exampl2e.com/",
                "landingPage": "https://example.com/",
                "ip": "198.168.0.4",
                "platform": "pcd",
                "browser": "chromed",
                "deviceType": "pcd",
                "device": "pcd",
                "MRR": 5,
                "trialStart": "2021-02-24T22:00:00.000Z",
                "trialEnd": "2021-02-28T22:00:00.000Z",
                "data": {
                    "unsubscribeReason": "testd"
                }
            }
        ]
    }
]

**Comment by ruxxzebre** [comment]
Thanks for response! 
Already fixed it.
